spec: 
  template:      
    spec:
      containers:
        - env:
            - name: REDIS_PW
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: redis